apiVersion: v1
kind: Service
metadata:
  name: rigguard-frontend
  namespace: rigguard
  labels:
    app: rigguard-frontend
spec:
  selector:
    app: rigguard-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
