apiVersion: v1
kind: Service
metadata:
  name: rigguard-prediction
  namespace: rigguard
  labels:
    app: rigguard-prediction
spec:
  selector:
    app: rigguard-prediction
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
