apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rigguard-api-hpa
  namespace: rigguard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rigguard-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rigguard-prediction-hpa
  namespace: rigguard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rigguard-prediction
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
